//
// Created by 86189 on 2021/8/26.
//

#ifndef COURSEMANAGE_CONFIG_H
#define COURSEMANAGE_CONFIG_H

#define  CONFIG_TEACHER_FUNCTION 1
#define  CONFIG_STUDENT_FUNCTION 1
#define  CONFIG_ADMIN_FUNCTION   0

#endif //COURSEMANAGE_CONFIG_H
